# This code was generated by dot2ruby.g

require 'rubygems'
require 'graphviz'
graph_g = GraphViz.digraph( "G" ) { |graph_g|
  graph_g[:bb] = '0,0,765.67,418'
  graph_cluster_user = graph_g.add_graph( "cluster_user" )
  graph_cluster_user[:bb] = '8,169,294,327'
  graph_cluster_user[:label] = 'User'
  graph_cluster_user[:lheight] = '0.21'
  graph_cluster_user[:lp] = '151,315.5'
  graph_cluster_user[:lwidth] = '0.47'
  graph_cluster_generatedassociationmethods = graph_cluster_user.add_graph( "cluster_generatedassociationmethods" )
  graph_cluster_generatedassociationmethods[:bb] = '20,177,281,252'
  graph_cluster_generatedassociationmethods[:label] = 'GeneratedAssociationMethods'
  graph_cluster_generatedassociationmethods[:lheight] = '0.21'
  graph_cluster_generatedassociationmethods[:lp] = '150.5,240.5'
  graph_cluster_generatedassociationmethods[:lwidth] = '3.07'
  node_user_skills = graph_cluster_generatedassociationmethods.add_nodes( "user_skills", :height => '0.5', :label => 'user_skills', :pos => '88,203', :width => '1.6728' )
  graph_cluster_generatedassociationmethods.add_edges( "user_skills", "user_skills", :pos => 'e,128.13,189.53 128.13,216.47 148.15,218.33 166,213.84 166,203 166,194.02 153.76,189.4 138.18,189.14' )
  graph_g.add_edges( "user_skills", "reader", :pos => 'e,279.06,68.329 120.46,187.84 136.83,181.21 157.17,173.74 176,169 201.66,162.54 214.01,177.11 235,161 260.86,141.15 272.31,104.09 277.3,78.505' )
  graph_g.add_edges( "user_skills", "association", :pos => 'e,150.03,68.198 95.894,184.97 108.02,158.8 131.35,108.49 145.71,77.518' )
  node_skills = graph_cluster_generatedassociationmethods.add_nodes( "skills", :height => '0.5', :label => 'skills', :pos => '220,203', :width => '0.97357' )
  graph_cluster_generatedassociationmethods.add_edges( "skills", "skills", :pos => 'e,244.53,189.99 244.53,216.01 259.2,218.9 273,214.56 273,203 273,194.15 264.91,189.53 254.54,189.15' )
  graph_g.add_edges( "skills", "reader", :pos => 'e,274.21,67.812 226.76,185.26 237.34,159.07 257.9,108.19 270.44,77.14' )
  graph_g.add_edges( "skills", "association", :pos => 'e,165.09,68.276 213.13,185.26 202.43,159.21 181.7,108.73 168.94,77.635' )
  node_add_skill = graph_cluster_user.add_nodes( "add_skill", :height => '0.5', :label => 'add_skill', :pos => '68,278', :width => '1.4305' )
  graph_cluster_user.add_edges( "add_skill", "user_skills", :pos => 'e,83.317,221.09 72.639,260.07 75.02,251.38 77.976,240.59 80.658,230.8' )
  graph_cluster_user.add_edges( "add_skill", "add_skill", :pos => 'e,102.79,264.61 102.79,291.39 120.78,293.45 137,288.98 137,278 137,269.16 126.5,264.55 113.02,264.15' )
  graph_g.add_edges( "add_skill", "create", :pos => 'e,459.08,68.335 108.34,266.71 120.67,264 134.31,261.44 147,260 162.84,258.2 709.8,263.35 721,252 746.9,225.73 746.59,195.56 721,169 704.41,151.78 525.8,174.39 506,161 478.45,142.37 466.22,104.42 460.9,78.351' )
  graph_g.add_edges( "add_skill", "__temp__9646", :pos => 'e,360.36,220.01 108.79,266.97 121.01,264.3 134.49,261.7 147,260 207.88,251.74 225.46,267.13 285,252 308.15,246.12 332.4,234.94 351.45,224.84' )
  node_has_skill_ = graph_cluster_user.add_nodes( "has_skill?", :height => '0.5', :label => 'has_skill?', :pos => '212,278', :width => '1.5402' )
  graph_cluster_user.add_edges( "has_skill?", "skills", :pos => 'e,218.12,221.18 213.9,259.7 214.82,251.25 215.96,240.87 217,231.37' )
  graph_cluster_user.add_edges( "has_skill?", "has_skill?", :pos => 'e,249.19,264.57 249.19,291.43 268.07,293.39 285,288.91 285,278 285,269.13 273.82,264.52 259.5,264.15' )
  graph_g.add_edges( "has_skill?", "include?", :pos => 'e,601.7,62.416 267.43,276.46 401.32,274.87 732.57,269.22 749,252 774.47,225.32 766.69,201.37 749,169 719.92,115.8 655.46,83.04 611.12,65.931' )
  node_reader = graph_cluster_collectionassociation.add_nodes( "reader", :height => '0.5', :label => 'reader', :pos => '281,50', :width => '1.1472' )
  node_create = graph_cluster_collectionproxy.add_nodes( "create", :height => '0.5', :label => 'create', :pos => '457,50', :width => '1.1152' )
  node_include_ = graph_cluster_collectionproxy.add_nodes( "include?", :height => '0.5', :label => 'include?', :pos => '565,50', :width => '1.3895' )
  node_association = graph_cluster_associations.add_nodes( "association", :height => '0.5', :label => 'association', :pos => '158,50', :width => '1.7506' )
  node___temp__9646 = graph_cluster_____class_0x007f90d189b2c8__0x007f90d189b340_.add_nodes( "__temp__9646", :height => '0.5', :label => '__temp__9646', :pos => '387,203', :width => '2.1437' )
  node_test_the_truth = graph_cluster_usertest.add_nodes( "test_the_truth", :height => '0.5', :label => 'test_the_truth', :pos => '146,361', :width => '2.1437' )
  graph_g.add_edges( "test_the_truth", "add_skill", :pos => 'e,83.609,295.21 129.84,343.22 118.5,331.44 103.18,315.53 90.629,302.5' )
  graph_g.add_edges( "test_the_truth", "has_skill?", :pos => 'e,198.57,295.48 159.68,343.22 169.03,331.74 181.58,316.33 192.05,303.49' )
}

graph_g.output( dot: "test.dot")
